### ISSUE TITLE
extreme slow speed for "--covar"

### ISSUE THREAD

**Issue by jiehuang001** [zhanxw/rvtests#25] opened 2017-04-29 10:54 UTC
Dear Xiaowei:

Please see the two screenshots below. It took me 54,799 seconds to analyze 225,216 samples and 94,238 SNPs, for a 5MB imputed chunk.

Now, when I use "--siteFile" to limit my analysis to 92 SNPs that are genome-wide significant in a 1MB region and use "--covar" to condition on the imputed dosage of the lead SNP. After 12 hours, the message "Analysis started" has not shown up yet. 

So, my SNP number goes down from 94,238 to 92, but the running time might be even longer, after I simply used one covariate! I don't know if RVTESTS can be optimized for this type of analysis. If not, can I adjust the covariate value in R first to create phenotype residual and then run RVTESTS without the "--covar" option?

Thank you & best regards,
Jie  

![capture](https://cloud.githubusercontent.com/assets/26947455/25554896/98f278e4-2ca7-11e7-8394-0431123b08e6.JPG)

![capture2](https://cloud.githubusercontent.com/assets/26947455/25554897/9c85c77c-2ca7-11e7-9ccf-9926686ec256.JPG)

**Comment by jiehuang001** [comment] 2017-04-30 05:20
hi, i just tested and found that the problem is with the --siteFile option. please see the two screenshots below, it took 43356 seconds to run a regression on 93 SNPs when I used --siteFile. But when i use bcftools first to extract those 93 SNPs to create a new VCF, which takes a minute, then it only took 109 second to run the same analysis 

![capture1](https://cloud.githubusercontent.com/assets/26947455/25561885/efe5b828-2d42-11e7-8cd8-e440dae0faea.JPG)

![capture2](https://cloud.githubusercontent.com/assets/26947455/25561887/fb44a9e0-2d42-11e7-9ea5-543d6d300635.JPG)

**Comment by zhanxw** [comment] 2017-06-15 22:53
This issue is essentially #26 . 
As I said in #26, when there are just a handful of SNPs, use `--rangeFile` will be more efficient.

**Comment by zhanxw** [comment] 2017-06-15 22:54
Since `--covar` is not the root cause for this issue, I close it for now.

**Closed by zhanxw** 2017-06-15 22:54 UTC
Labels: need_further_investigation
